# This workflow checks if it's time to generate the next beta relnotes.
# And if so, it generates the beta relnotes and opens a PR with them.

name: Generate beta relnotes

on:
  workflow_dispatch:
  schedule:
    # once a day
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  generate:
    name: Check if it's time and generate beta relnotes
    runs-on: ubuntu
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd scripts
          npm install
      - name: Run script
        id: generate
        run: |
          cd scripts
          node web-platform-release-notes.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "New Edge Beta web platform release notes"
          title: "New Edge Beta web platform release notes"
          body: "This PR was generated by the workflow to update the beta release notes."
          branch: "web-platform-release-notes"
          base: "main"
          branch-suffix: timestamp
          labels: "web-platform-release-notes"
          reviewers: "mikehoffms,captainbrosset,aluhrs13"
          assignees: "captainbrosset"
